spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?characterEncoding=utf8&serverTimezone=UTC
    username: admin
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


jwt:
    secret: 8d64ddc4c0baef3697aaeb709ffab5ccf18a89fd7a1510eadb1987337658d22688b67d32955573bab5e594c86a6e23b914ea59744025573ff5d4eb55fc2fb223f145b74b3e19b2228ca7088cd9a7d4162380b80115cd65911251fe59cdf6d927cb1afdc2d64f169e684b069db4a5461fe2c19913709492b01c448cbcf74492ac
    expiration: 86400 # 1 day in seconds
    issuer: myapp
    audience: myapp-users