spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://svc.sel4.cloudtype.app:30642/demo_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  # 서버 설정 추가
  mvc:
    contentnegotiation:
      favor-parameter: false
      favor-path-extension: false
      ignore-accept-header: false
      default-content-type: application/json
    cors:
      mappings:
        "/**":
          allowed-origins: "http://localhost:5173,https://study-deploy-frontend.vercel.app"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "Content-Type,Authorization,Accept,X-Requested-With"
          exposed-headers: "Authorization"
          allow-credentials: true
          max-age: 3600

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.web.cors: INFO
    com.ssafy.demo: INFO
    org.hibernate: INFO

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  tomcat:
    remoteip:
      protocol-header: x-forwarded-proto
      remote-ip-header: x-forwarded-for
    basedir: .

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:6781ee3f7bbb335f7285c646bee0032478280335400ce6ac70f76f2ded5a319a6168fb8f56d3e26659a8d95d6ad1f568eaab227a4346360e5a837ffdd184c89cc7a504eeadab54d35720b52ed4048056ee3b38c5e40e813e810c619dd47290b655d639674dae4a503008a246b15d62d596e052375ebd4d471feb367c1484f4b5}
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY:86400}
