version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: demo-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-time-zone=UTC"
      ]
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
